### ISSUE TITLE
Align CPU types b/w SCS and Gaia-X

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/gx-self-description-generator#13]
https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0100-v3-flavor-naming.md
has this table for CPUs

Generation | i (Intel x86-64) | z (AMD x86-64) | a (AArch64) | r (RISC-V)
-- | -- | -- | -- | --
0 | pre Skylake | pre Zen | pre Cortex A76 | TBD
1 | Skylake | Zen-1 (Naples) | A76/NeoN1 class | TBD
2 | Cascade Lake | Zen-2 (Rome) | A78/x1/NeoV1 class | TBD
3 | Ice Lake | Zen-3 (Milan) | Anext/NeoN2 class | TBD

while the flavor spec in Gaia-X has
    exampleValues: [ 'Skylake-Server-v4', 'Icelake-Server-v4', 'Cascadelake-Server-v4', 'EPYC-Milan-v1', 'EPYC-Rome-v2' ]

We can translate this except for the -vN suffix in Gaia-X.

**Comment by garloff** [comment]
Obviously, the Gaia-X values don't necessarily need to match the SCS classification literally, but a unique 1:1 relationship would be nice.
E.g. -i1 = Skylake, -i3 = Icelake, -z2 = Rome, -a2 = Cortex-A78.
# exampleValues: ['Skylake', 'Cascadelake', 'Icelake', 'Cascadelake', 'Naples', 'Rome', 'Milan', 'Cortex-A78']
The question is whether we need to disallow variants (like CometLake -> Skylake and Rocketlake -> Icelake)?

**Comment by anjastrunk** [comment]
duplicate to #63
